name: ⚡ Execute VPS Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute on VPS'
        required: true
        default: 'uptime'

jobs:
  exec:
    runs-on: self-hosted
    steps:
      - name: Execute Command
        run: ${{ github.event.inputs.command }}
